{{- if and (not .Values.global.api.users.director.password) (not .Values.global.api.users.credSecret) (not .Values.global.api.users.director.password.secretKey)}}
apiVersion: v1
kind: Secret
metadata: 
  name: api.director
data:
  director_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
{{- end}}
---
{{- if and (not .Values.global.api.users.icingaweb.password) (not .Values.global.api.users.credSecret) (not .Values.global.api.users.icingaweb.password.secretKey)}}
apiVersion: v1
kind: Secret
metadata: 
  name: api.icingaweb
data:
  icingaweb_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
{{- end}}
---
apiVersion: v1
kind: Secret
metadata: 
  name: database.director
data:
  director_username: director
  director_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
