{{- if and (not .Values.global.api.users.director.password) (not .Values.global.api.users.credSecret) (not .Values.global.api.users.director.password.secretKey)}}
apiVersion: v1
kind: Secret
metadata: 
  name: api.director
data:
  director_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
{{- end}}
---
{{- if and (not .Values.global.api.users.icingaweb.password) (not .Values.global.api.users.credSecret) (not .Values.global.api.users.icingaweb.password.secretKey)}}
apiVersion: v1
kind: Secret
metadata: 
  name: api.icingaweb
data:
  icingaweb_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
{{- end}}
---
{{- if or (and (not .Values.global.databases.director.username) (not .Values.global.databases.director.credSecret) (not .Values.global.databases.director.username.secretKey))
(and (not .Values.global.databases.director.password) (not .Values.global.databases.director.credSecret) (not .Values.global.databases.director.password.secretKey))}}
apiVersion: v1
kind: Secret
metadata: 
  name: database.director
data:
  director_username: director
  director_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
{{- end}}
---
{{- if or (and (not .Values.global.databases.icingaweb2.username) (not .Values.global.databases.icingaweb2.credSecret) (not .Values.global.databases.icingaweb2.username.secretKey)) 
(and (not .Values.global.databases.icingaweb2.password) (not .Values.global.databases.icingaweb2.credSecret) (not .Values.global.databases.icingaweb2.password.secretKey))}}
apiVersion: v1
kind: Secret
metadata: 
  name: database.icingaweb2
data:
  icingaweb2_username: icingaweb2
  icingaweb2_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
{{- end}}
---
{{- if or (and (not .Values.global.databases.icingadb.username) (not .Values.global.databases.icingadb.credSecret) (not .Values.global.databases.icingadb.username.secretKey)) 
(and (not .Values.global.databases.icingadb.password) (not .Values.global.databases.icingadb.credSecret) (not .Values.global.databases.icingadb.password.secretKey))}}
apiVersion: v1
kind: Secret
metadata: 
  name: database.icingadb
data:
  icingadb_username: icingadb
  icingadb_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
{{- end}}
---
{{- if or (and (not .Values.global.databases.kubernetes.username) (not .Values.global.databases.kubernetes.credSecret) (not .Values.global.databases.kubernetes.username.secretKey)) 
(and (not .Values.global.databases.kubernetes.password) (not .Values.global.databases.kubernetes.credSecret) (not .Values.global.databases.kubernetes.password.secretKey))}}
apiVersion: v1
kind: Secret
metadata: 
  name: database.kubernetes
data:
  kubernetes_username: kubernetes
  kubernetes_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
{{- end}}