{{- if and (not .Values.auth.admin_password.value) (not .Values.auth.admin_password.credSecret) (not .Values.auth.admin_password.secretKey)}}
apiVersion: v1
kind: Secret
metadata: 
  name: icingaweb2
data:
  auth_password: {{ randAlphaNum 32 | b64enc }}
type: Opaque
{{- end}}